### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by bookerthegeek** [mallrat208/UBC-Ore-Registrar#22]
Hello @mallrat208, How are you today?

I was just wondering if you noticed that  [Underground Biome Constructs](https://github.com/Zeno410/UndergroundBiomesConstructs1.10) has updated to 1.10? I'm sure you did but thought I would poke you about it anyways. 

Moving on, I was pondering on if you had any motivation on supporting the new version? If you do... I look forward to my unified UBC world generation. 

If not, that is ok also, 😭 although my subterranean  world will not be nearly as pretty and unified as it could be.

Thank you and have a wonderful day!

**Comment by mallrat208** [comment]
I honestly haven't been keeping up with it, for a long time performance in
1.10.2 was poor enough for a while that I wouldn't even consider UBC.

I'll give it a look later on Sunday to see what an update would take

On Mar 5, 2017 2:52 AM, "BookerTheGeek" <notifications@github.com> wrote:

Hello @mallrat208 <https://github.com/mallrat208>, How are you today?

I was just wondering if you noticed that Underground Biome Constructs
<https://github.com/Zeno410/UndergroundBiomesConstructs1.10> has updated to
1.10? I'm sure you did but thought I would poke you about it anyways.

Moving on, I was pondering on if you had any motivation on supporting the
new version? If you do... I look forward to my unified UBC world generation.

If not, that is ok also, 😭 although my subterranean world will not be
nearly as pretty as it could be.

Thank you and have a wonderful day!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mallrat208/UBC-Ore-Registrar/issues/22>, or mute the
thread

**Comment by mallrat208** [comment]
As a quick update

The changes to UBC are not that bad in terms of implementation (and holy cow does it generate stone quicker)  but I'll probably need to do a complete rewrite rather than a straight up port.

**Comment by bookerthegeek** [comment]
Whatever is best. And yeah it has inproved alot. Looking forward to seeing what you can do with this. Good luck!

**Comment by mallrat208** [comment]
I'll have an initial build for 1.10.2 up later today.

To start with I've removed all mods supported as a large number of them no longer exist, I'll go through, see what still exists and add those back.

**Comment by bookerthegeek** [comment]
All the ones I've linked are 1.10, I'll get you a list tonight of most of the ore adding mods and post them here for you.

**Comment by bookerthegeek** [comment]
Is there anything mods can do to help with compatablilty, or is it all in your mod?

**Comment by mallrat208** [comment]
The only thing another mod has to do is register their block during preInit. There are a few that didn't in 1.7.10, Project Red for example.  Before I was able to feed a null into the process where UBC would create the UBified ores, that's not an option anymore. Everything must happen during preInit.

**Comment by bookerthegeek** [comment]
Gotcha. I'll go inform all thos wonderful other mod authors i kept bugging about that and maybe soon ill be able to have a unified subterranean world to mess with my players even more.

Also probably a good time to let you know I'll be using this in a pack in case you wanted to know. Or if you hate your life and love dark souls you could come play sometime. :)

**Comment by mallrat208** [comment]
I've run into two bugs with UBC while porting this which may delay release, they're already posted on the UBC issue tracker but it may take a bit for a response.

Ores receive the incorrect OreDictionary tags.
Ores Register with non-unique IDs

The first one is annoying and may break some mod processing chains, but it doesn't crash
The second one will cause a crash until fixed and there's nothing I can do short of partly rewriting some UBC stuff manually.

**Comment by bookerthegeek** [comment]
Well crap sticks.

**Comment by mallrat208** [comment]
Pretty much.

I'm going to use the time waiting for a reply to just add additional mod support. If you have any requests submit them as a post to #24 

I'm going to go ahead and close this out for now.
